import React, { useState, useEffect } from 'react';
import { FileCode2, Package, Code2, AlertCircle } from 'lucide-react';
import { apiClient } from '../../api/client';

interface TeamArtifactsPanelProps {
  team: any;
  runId?: string;
}

const TeamArtifactsPanel: React.FC<TeamArtifactsPanelProps> = ({ team, runId }) => {
  const [artifacts, setArtifacts] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    let interval: any;
    const fetchArtifacts = async () => {
      if (!runId) return;
      try {
        const res = await apiClient.get(`/api/teams/runs/${runId}/artifacts`);
        setArtifacts(res.artifacts || []);
      } catch (err) {
        console.error('Failed to fetch artifacts', err);
      }
    };

    fetchArtifacts();

    if (team?.status === 'running' || team?.status === 'paused') {
      interval = setInterval(fetchArtifacts, 3000);
    }
    return () => clearInterval(interval);
  }, [runId, team?.status]);

  return (
    <div className="flex flex-col h-full">
      <div className="p-4 border-b border-gray-800 shrink-0">
        <h2 className="text-sm font-semibold text-gray-200 uppercase tracking-wider flex items-center gap-2">
          <Package size={16} className="text-purple-400" />
          Checkpoint Artifacts
        </h2>
        <p className="text-xs text-gray-500 mt-1">Files modified and generated by the team</p>
      </div>

      <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-3">
        {!runId || artifacts.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-center text-gray-500 gap-3 opacity-50">
            <Package size={32} />
            <p className="text-sm">No artifacts generated yet.</p>
          </div>
        ) : (
          artifacts.map(artifact => (
            <div key={artifact.id} className="bg-[#1A1A1E] border border-gray-800 rounded-lg p-3 hover:border-gray-700 cursor-pointer transition-colors flex items-start gap-3">
              <div className="w-8 h-8 rounded bg-blue-500/10 flex items-center justify-center shrink-0">
                <FileCode2 size={16} className="text-blue-400" />
              </div>
              <div className="overflow-hidden">
                <h4 className="text-sm font-medium text-gray-200 truncate">{artifact.path}</h4>
                <p className="text-xs text-gray-500 mt-0.5">Size: {artifact.size} bytes</p>
                {artifact.verifiedAt && <p className="text-xs text-emerald-500 mt-0.5">Verified</p>}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default TeamArtifactsPanel;
