"""identity_both_directions.py -- operator R4 (APPROVAL BEFORE EXTERNAL ACTION), both directions, ONE run.

It shows, in a single execution against a THROWAWAY root:
  A. the SHIPPED guard (approval_queue.py:55-57 denylist, checked at :153) ACCEPTS the
     machine identities hermes-agent / assistant / claude / the monitor  -> the bypass
  B. the PROPOSED allowlist gate REFUSES hermes-agent (exit 4) and ACCEPTS the operator
     name (exit 0)  -> both directions, real exit codes, subprocess
  C. the PROPOSED patched module refuses hermes-agent at the decision site itself
  D. an accepted decision records decided_by AND the frozen fields survive
  E. even when the SHIPPED guard lets a machine identity sign, the frozen fields still hold
     -> attribution property (broken) and safety property (intact) are stated separately

monitoring/freecash/** is never modified: the shipped module comes from routine_copy, the
patched module from proposed/ (generated by make_allowlist_variant.py).

Usage: python identity_both_directions.py <root> <routine_copy> <proposed_dir>
"""

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(sys.argv[1])
ROUTINE = sys.argv[2]
PROPOSED = sys.argv[3]

OPERATOR_NAME = "the operator"  # placeholder for the human's own name; written into the throwaway allowlist
MACHINE_NAMES = ("hermes-agent", "assistant", "claude", "the monitor")

os.environ["FREECASH_DATA_ROOT"] = str(ROOT)
os.environ["FREECASH_TZ"] = "Europe/Berlin"
os.environ.setdefault("AGENT_TEAMS_DB_PATH", str(ROOT.parent / "agent-teams.db"))
os.environ.setdefault("AGENTICOS_DATA_DIR", str(ROOT.parent / "agenticos-data"))

sys.path.insert(0, ROUTINE)
sys.path.insert(0, str(ROUTINE))
sys.path.insert(1, PROPOSED)

import approval_queue  # noqa: E402  (shipped, from routine_copy)
import paths  # noqa: E402

sys.path.insert(0, PROPOSED)
import approval_queue_allowlist  # noqa: E402  (proposed variant, generated)


def bar(title):
    print("\n" + "=" * 78)
    print(title)
    print("=" * 78)


def write_allowlist():
    state = ROOT / "state"
    state.mkdir(parents=True, exist_ok=True)
    (state / "human-deciders.json").write_text(
        json.dumps(
            {
                "schema_version": 1,
                "kind": "human_deciders_allowlist",
                "note": "throwaway root: the operator's own name goes here in production",
                "deciders": [OPERATOR_NAME],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def main() -> int:
    failures = []
    print("root: %s" % ROOT)
    print("env pins: FREECASH_DATA_ROOT=%s AGENT_TEAMS_DB_PATH=%s AGENTICOS_DATA_DIR=%s"
          % (os.environ["FREECASH_DATA_ROOT"], os.environ["AGENT_TEAMS_DB_PATH"],
             os.environ["AGENTICOS_DATA_DIR"]))
    paths.ensure_layout()
    write_allowlist()
    print("wrote %s" % (ROOT / "state" / "human-deciders.json"))
    print("shipped module : %s" % approval_queue.__file__)
    print("proposed module: %s" % approval_queue_allowlist.__file__)

    change = {"change_type": "EARNINGS_CHANGED", "field": "earnings_total_cents",
              "old_value": 1025, "new_value": 1340, "dedupe_key": "demo-key"}

    bar("A. SHIPPED GUARD (denylist at approval_queue.py:55-57, checked :153) -- THE BYPASS")
    for name in MACHINE_NAMES + (OPERATOR_NAME,):
        try:
            accepted = approval_queue._normalise_decider(name)
            print("  _normalise_decider(%-13r) -> ACCEPTED as %r   <-- machine can sign" % (name, accepted))
        except approval_queue.NotHumanError as exc:
            print("  _normalise_decider(%-13r) -> REFUSED: %s" % (name, exc))
    print("  RESULT: 4 machine identities are ACCEPTED by the shipped guard. R4's stated "
          "property 'only a human can sign' is FALSE as shipped.")

    bar("B. PROPOSED ALLOWLIST GATE -- BOTH DIRECTIONS, ONE RUN, REAL EXIT CODES")
    gate = str(Path(PROPOSED) / "identity_gate.py")
    env = dict(os.environ)
    for name in ("hermes-agent", OPERATOR_NAME):
        print("\n$ python %s --by %r --root %s" % (gate, name, ROOT))
        completed = subprocess.run([sys.executable, gate, "--by", name, "--root", str(ROOT)],
                                   capture_output=True, text=True, env=env)
        print(completed.stdout.rstrip())
        if completed.stderr.strip():
            print("stderr: %s" % completed.stderr.rstrip())
        print("EXIT=%d" % completed.returncode)
        if name == "hermes-agent" and completed.returncode == 0:
            failures.append("the proposed gate accepted hermes-agent")
        if name == OPERATOR_NAME and completed.returncode != 0:
            failures.append("the proposed gate refused the operator name")
    print("\nRED   : identity_gate.py exits 4 (REFUSED) on the machine identity 'hermes-agent'")
    print("GREEN : identity_gate.py exits 0 (ACCEPTED) on the operator identity %r" % OPERATOR_NAME)

    bar("C. PROPOSED PATCHED MODULE -- refusal at the decision site itself")
    try:
        item = approval_queue.enqueue("2026-10-01", change, "demo: earnings moved")
        approval_queue_allowlist.decide(item["approval_id"], "approve", "hermes-agent", "attempted machine sign-off")
        print("  decide(by='hermes-agent') -> ACCEPTED  <-- DEFECT")
        failures.append("the patched module accepted hermes-agent")
    except approval_queue_allowlist.NotHumanError as exc:
        print("  approval_queue_allowlist.decide(by='hermes-agent') -> REFUSED")
        print("  NotHumanError: %s" % exc)

    bar("D. PROPOSED PATCHED MODULE -- accepted decision, attribution + frozen fields")
    item = approval_queue.enqueue("2026-10-01", change, "demo: earnings moved")
    decided = approval_queue_allowlist.decide(item["approval_id"], "approve", OPERATOR_NAME,
                                              "read the change myself; no action wanted")
    print("  decided_by                       = %r   (ATTRIBUTION: who signed)" % decided["decided_by"])
    print("  status                           = %r" % decided["status"])
    print("  execution_state                  = %r   (FROZEN)" % decided["execution_state"])
    print("  expires_at_utc                   = %r   (FROZEN: no expiry, so nothing can 'expire into' execution)" % decided["expires_at_utc"])
    print("  execution_allowed_by_this_routine= %r   (FROZEN)" % decided["execution_allowed_by_this_routine"])
    if decided["execution_state"] != "NOT_EXECUTED" or decided["expires_at_utc"] is not None:
        failures.append("frozen fields moved on an approved item")

    bar("E. SEPARATE THE TWO PROPERTIES -- shipped guard signs with a machine identity")
    item2 = approval_queue.enqueue("2026-10-01", change, "demo: earnings moved")
    bad = approval_queue.decide(item2["approval_id"], "approve", "hermes-agent",
                                "shipped guard accepted this name")
    print("  ATTRIBUTION property : decided_by=%r  status=%r   <-- BROKEN as shipped" % (bad["decided_by"], bad["status"]))
    print("  SAFETY property      : execution_state=%r expires_at_utc=%r execution_allowed=%r   <-- INTACT"
          % (bad["execution_state"], bad["expires_at_utc"], bad["execution_allowed_by_this_routine"]))
    print("  The two failures are independent: fixing attribution does not depend on the frozen "
          "fields, and the frozen fields do not rescue a false attribution.")
    if bad["execution_state"] != "NOT_EXECUTED" or bad["expires_at_utc"] is not None or bad["execution_allowed_by_this_routine"] is not False:
        failures.append("frozen fields were armed by a machine-signed decision")

    bar("VERDICT")
    for item in failures:
        print("OPEN DEFECT: %s" % item)
    print("RESULT: %s" % ("PASS -- hermes-agent REFUSED, operator ACCEPTED, frozen fields intact"
                          if not failures else "FAIL"))
    print("decided.jsonl lines: %d" % len(paths.read_jsonl(paths.decided_path())))
    print("pending.json exists: %s" % paths.pending_path().exists())
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
