import { db } from './src/db/index.js';
import { generatedAssets, revenueOpportunities, productionBriefs } from './src/db/schema.js';
import crypto from 'crypto';

async function mock() {
  try {
    const oppId = crypto.randomUUID();
    const briefId = crypto.randomUUID();
    const assetId = crypto.randomUUID();
    const now = new Date().toISOString();

    // 1. Create Mock Opportunity
    await db.insert(revenueOpportunities).values({
      id: oppId,
      title: 'Mock Synthetic Staging Opportunity',
      description: 'Opportunity to test staging workflow',
      opportunityType: 'ecommerce',
      stage: 'approved',
      approvalStatus: 'approved',
      createdAt: now,
      updatedAt: now
    });

    // 2. Create Mock Brief
    await db.insert(productionBriefs).values({
      id: briefId,
      opportunityId: oppId,
      status: 'ready_for_generation',
      createdAt: now,
      updatedAt: now
    });

    // 3. Create Mock Asset ready for review
    await db.insert(generatedAssets).values({
      id: assetId,
      briefId: briefId,
      opportunityId: oppId,
      assetType: 'ugc_video',
      title: 'UGC Video Script - TikTok Hook',
      content: 'This is an amazing script generated by Hermes.',
      status: 'ready_for_review',
      createdAt: now,
      updatedAt: now
    });

    console.log('Mocked asset ID:', assetId);
    process.exit(0);
  } catch (e) {
    console.error(e);
    process.exit(1);
  }
}
mock();
