import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const goalRuns = sqliteTable('goal_runs', {
  goalId: text('goal_id').primaryKey(),
  conversationId: text('conversation_id').notNull(),
  turnId: text('turn_id'),
  originalUserInput: text('original_user_input').notNull(),
  normalizedGoal: text('normalized_goal').notNull(),
  status: text('status').notNull(),
  plan: text('plan', { mode: 'json' }).$type<any>(),
  attempts: text('attempts', { mode: 'json' }).$type<any[]>().notNull(),
  currentAttempt: integer('current_attempt').notNull().default(1),
  capabilitiesUsed: text('capabilities_used', { mode: 'json' }).$type<string[]>().notNull(),
  evidence: text('evidence', { mode: 'json' }).$type<any[]>().notNull(),
  failures: text('failures', { mode: 'json' }).$type<any[]>().notNull(),
  recoveryIncidentId: text('recovery_incident_id'),
  finalVerification: text('final_verification', { mode: 'json' }).$type<any>(),
  learnedResolution: text('learned_resolution', { mode: 'json' }).$type<any>(),
  timeline: text('timeline', { mode: 'json' }).$type<any[]>().notNull(),
  acknowledgementText: text('acknowledgement_text'),
  finalResponseText: text('final_response_text'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});

export const repairKnowledge = sqliteTable('repair_knowledge', {
  id: text('id').primaryKey(),
  failureSignature: text('failure_signature').notNull(),
  goalType: text('goal_type').notNull(),
  target: text('target').notNull(),
  environment: text('environment').notNull(),
  failedStrategy: text('failed_strategy').notNull(),
  successfulStrategy: text('successful_strategy').notNull(),
  resolvedTarget: text('resolved_target').notNull(),
  surface: text('surface').notNull(),
  executablePath: text('executable_path'),
  resolvedCommand: text('resolved_command'),
  url: text('url'),
  requiredParams: text('required_params', { mode: 'json' }).$type<Record<string, any>>(),
  verificationMethod: text('verification_method').notNull(),
  repairSource: text('repair_source').notNull(),
  confidence: real('confidence').notNull(),
  lastValidatedAt: text('last_validated_at').notNull(),
});
