import {describe,it,expect,beforeEach,afterEach} from 'vitest';
import Database from 'better-sqlite3';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {IndependentVerificationGate,evidenceHash,isCurrentVerificationProof,type VerificationBinding,type IndependentObservation} from '../domains/controlPlane/taskGraph/IndependentVerificationGate.js';
describe('independent verification gate',()=>{
 let db:Database.Database;let now:number;let b:VerificationBinding;let evidence:IndependentObservation;
 beforeEach(()=>{db=new Database(':memory:');now=1000;b={goalId:'goal',graphId:'graph',nodeId:'node',operation:'read',attempt:1,workerId:'worker',producer:{actorId:'handler',executionPath:'handler.read'},policyRef:'controlled-file',policyVersion:1,approval:{required:false,state:'NOT_REQUIRED',reference:'controlled-file-exemption-v1'},postcondition:{id:'matches',definition:'file digest equals requested contents',expectedHash:evidenceHash('Inspect\nexecute\nverify')},argumentHash:evidenceHash('args'),resourceHash:evidenceHash('file'),evidenceVersion:1,expiresAt:2000};evidence={hash:b.postcondition.expectedHash,sourceId:'fs-descriptor',observedAt:now,validUntil:1900,version:1};});
 afterEach(()=>db.close());
 function gate(observe=async()=>evidence,actorId='observer',executionPath='observer.read'){const authoritative=JSON.stringify(b);return new IndependentVerificationGate(db,{now:()=>now,validateBinding:input=>JSON.stringify(input)===authoritative,resolvePolicy:(ref,version)=>ref==='controlled-file'&&version===1?{approvalRequired:false,approvalReference:'controlled-file-exemption-v1'}:undefined,observers:[{id:'observer',actorId,executionPath,observe}]});}
 function succeeded(g:IndependentVerificationGate){const id=g.begin(b);expect(g.recordSuccess(id)).toBe('SUCCEEDED');return id;}
 it('handler success alone never verifies',()=>{const g=gate(),id=succeeded(g);expect(()=>g.promote(id)).toThrow('INDEPENDENT_EVIDENCE_MISSING');expect(g.status(id)).toBe('SUCCEEDED');});
 it.each(['actor','path'])('rejects same-handler verification by %s',async dimension=>{const g=gate(undefined,dimension==='actor'?'handler':'observer',dimension==='path'?'handler.read':'observer.read');const id=succeeded(g);await expect(g.runObserver(id,'observer')).rejects.toThrow('SELF_VERIFICATION');});
 it.each(['goalId','graphId','nodeId','operation','workerId','policyRef','postcondition','approval'])('rejects missing %s',field=>{delete (b as any)[field];expect(()=>gate().begin(b)).toThrow();});
 it('required approval fails closed without independently validated reference',()=>{b.approval={required:true,state:'VERIFIED',reference:'claimed'};expect(()=>gate().begin(b)).toThrow('APPROVAL_UNVERIFIED');});
 it('required approval missing reference fails',()=>{b.approval={required:true,state:'VERIFIED'};expect(()=>gate().begin(b)).toThrow('APPROVAL_UNVERIFIED');});
 it('expired receipt fails',()=>{const g=gate(),id=succeeded(g);now=2000;expect(()=>g.promote(id)).toThrow('EXPIRED');});
 it('cancellation rejects late evidence',async()=>{let release!:()=>void;const wait=new Promise<void>(r=>release=r);const g=gate(async()=>{await wait;return evidence;});const id=succeeded(g);const pending=g.runObserver(id,'observer');g.cancelGoal(b.goalId);release();await expect(pending).rejects.toThrow('CANCELLED');expect(()=>g.promote(id)).toThrow('CANCELLED');});
 it('observes durable goal cancellation',()=>{db.exec('CREATE TABLE goal_runs(goal_id TEXT,status TEXT)');const g=gate(),id=succeeded(g);db.prepare('INSERT INTO goal_runs VALUES(?,?)').run(b.goalId,'CANCELLED');expect(()=>g.promote(id)).toThrow('CANCELLED');});
 it.each(['version','timestamp','expiry','hash','source'])('rejects missing or stale evidence %s',async kind=>{const g=gate(),id=succeeded(g);if(kind==='version')evidence.version=2;if(kind==='timestamp')evidence.observedAt=999;if(kind==='expiry')evidence.validUntil=1000;if(kind==='hash')evidence.hash='';if(kind==='source')evidence.sourceId='';await expect(g.runObserver(id,'observer')).rejects.toThrow();expect(()=>g.promote(id)).toThrow('INDEPENDENT_EVIDENCE_MISSING');});
 it('contradiction poisons receipt and cannot be replaced',async()=>{const g=gate(),id=succeeded(g);evidence.hash=evidenceHash('different');await expect(g.runObserver(id,'observer')).rejects.toThrow('CONTRADICTORY');evidence.hash=b.postcondition.expectedHash;await expect(g.runObserver(id,'observer')).rejects.toThrow('CONTRADICTORY');expect(()=>g.promote(id)).toThrow('CONTRADICTORY');});
 it('independently reads actual temporary file and verifies exact digest once',async()=>{const dir=await mkdtemp(join(tmpdir(),'independent-observer-'));try{const path=join(dir,'file.txt');await writeFile(path,'Inspect\nexecute\nverify');const g=gate(async()=>({...evidence,hash:evidenceHash(await readFile(path,'utf8')),sourceId:`descriptor:${path}`}));const id=succeeded(g);await g.runObserver(id,'observer');const proof=g.promote(id);expect(proof.evidence.hash).toBe(b.postcondition.expectedHash);expect(g.status(id)).toBe('VERIFIED');expect(()=>g.promote(id)).toThrow('REPLAY');expect(()=>g.begin(b)).toThrow();}finally{await rm(dir,{recursive:true,force:true});}});
 it('pending observer prevents promotion and concurrent evidence CAS rejects stale writer',async()=>{const releases:Array<()=>void>=[];const g=gate(async()=>{await new Promise<void>(r=>releases.push(r));return {...evidence};});const id=succeeded(g);const first=g.runObserver(id,'observer'),second=g.runObserver(id,'observer');releases[0]();await first;expect(()=>g.promote(id)).toThrow('OBSERVER_PENDING');releases[1]();await expect(second).rejects.toThrow('STALE_GENERATION');expect(g.promote(id).receiptId).toBe(id);});
 it('concurrent contradictory evidence blocks promotion',async()=>{let release!:()=>void;let count=0;const g=gate(async()=>{if(++count===2){await new Promise<void>(r=>release=r);return {...evidence,hash:evidenceHash('changed')};}return evidence;});const id=succeeded(g);await g.runObserver(id,'observer');const other=g.runObserver(id,'observer');expect(()=>g.promote(id)).toThrow('OBSERVER_PENDING');release();await expect(other).rejects.toThrow('CONTRADICTORY');expect(()=>g.promote(id)).toThrow('CONTRADICTORY');});
 it('atomic commit rolls back promotion if journal append fails',async()=>{const g=gate(),id=succeeded(g);await g.runObserver(id,'observer');expect(()=>g.promote(id,()=>{throw Error('journal failure');})).toThrow('journal failure');expect(g.status(id)).toBe('SUCCEEDED');});
 it('expiry between observation and promotion blocks verification',async()=>{const g=gate(),id=succeeded(g);await g.runObserver(id,'observer');now=1900;expect(()=>g.promote(id)).toThrow('STALE_EVIDENCE');});
 it('proof cannot be forged, reused across goals or retained after cancellation',async()=>{const g=gate(),id=succeeded(g);await g.runObserver(id,'observer');const proof=g.promote(id);expect(isCurrentVerificationProof(proof,b.goalId)).toBe(true);expect(isCurrentVerificationProof({...proof},b.goalId)).toBe(false);expect(isCurrentVerificationProof(proof,'other')).toBe(false);g.cancelGoal(b.goalId);expect(isCurrentVerificationProof(proof,b.goalId)).toBe(false);});
 it('mutated and expired proof capabilities are rejected',async()=>{const g=gate(),id=succeeded(g);await g.runObserver(id,'observer');const proof=g.promote(id);proof.binding.workerId='impostor';expect(isCurrentVerificationProof(proof,b.goalId)).toBe(false);proof.binding.workerId=b.workerId;now=1900;expect(isCurrentVerificationProof(proof,b.goalId)).toBe(false);});
 it('requires explicit approval exemption reference',()=>{delete b.approval.reference;expect(()=>gate().begin(b)).toThrow('APPROVAL_UNVERIFIED');});
 it('cannot downgrade approval requirement from trusted policy',()=>{const g=new IndependentVerificationGate(db,{observers:[],now:()=>now,validateBinding:()=>true,resolvePolicy:()=>({approvalRequired:true,approvalReference:'human-required'})});expect(()=>g.begin(b)).toThrow('APPROVAL_UNVERIFIED');});
 it('missing canonical resolver denies nonexistent goals',()=>{const g=new IndependentVerificationGate(db,{observers:[],now:()=>now,resolvePolicy:()=>({approvalRequired:false,approvalReference:b.approval.reference!})});expect(()=>g.begin(b)).toThrow('CANONICAL_BINDING_UNVERIFIED');});
 it('canonical resolver rejects goal substitution',()=>{const g=gate();b.goalId='nonexistent';expect(()=>g.begin(b)).toThrow('CANONICAL_BINDING_UNVERIFIED');});
 it('missing policy resolver denies verification',()=>{const g=new IndependentVerificationGate(db,{observers:[],now:()=>now,validateBinding:()=>true});expect(()=>g.begin(b)).toThrow('POLICY_UNVERIFIED');});
 it.each(['sourceId','observedAt','validUntil','hash','version'])('revalidates corrupted persisted evidence %s at promotion',async field=>{const g=gate(),id=succeeded(g);await g.runObserver(id,'observer');const changed={...evidence,[field]:field==='sourceId'||field==='hash'?'':null};db.prepare('UPDATE independent_verification_receipts SET evidence=? WHERE id=?').run(JSON.stringify(changed),id);expect(()=>g.promote(id)).toThrow();});
 it('rejects persisted observer identity substitution',async()=>{const g=gate(),id=succeeded(g);await g.runObserver(id,'observer');db.prepare('UPDATE independent_verification_receipts SET observer=? WHERE id=?').run(JSON.stringify({id:'observer',actorId:'forged',executionPath:'forged'}),id);expect(()=>g.promote(id)).toThrow('SELF_VERIFICATION');});
 it('rejects async transaction commit before invoking callback',async()=>{const g=gate(),id=succeeded(g);await g.runObserver(id,'observer');let called=false;expect(()=>g.promote(id,async()=>{called=true;})).toThrow('ASYNC_COMMIT_FORBIDDEN');expect(called).toBe(false);expect(g.status(id)).toBe('SUCCEEDED');});
 it('rolls back a thenable-returning transaction commit',async()=>{const g=gate(),id=succeeded(g);await g.runObserver(id,'observer');expect(()=>g.promote(id,()=>({then(){}} as any))).toThrow('ASYNC_COMMIT_FORBIDDEN');expect(g.status(id)).toBe('SUCCEEDED');});
 it.each(['attempt','evidenceVersion','expiresAt','policyVersion','argumentHash','resourceHash'])('rejects absent binding field %s',field=>{delete (b as any)[field];expect(()=>gate().begin(b)).toThrow();});
 it.each(['workerId','operation','attempt','argumentHash','resourceHash','graphId','nodeId'])('canonical authority rejects substituted %s',field=>{const g=gate();(b as any)[field]=field==='attempt'?2:field.endsWith('Hash')?evidenceHash('substitution'):'substitution';expect(()=>g.begin(b)).toThrow('CANONICAL_BINDING_UNVERIFIED');});
 it.each(['policyRef','policyVersion'])('trusted policy rejects substituted %s',field=>{const g=gate();(b as any)[field]=field==='policyVersion'?2:'other-policy';expect(()=>g.begin(b)).toThrow('POLICY_UNVERIFIED');});
 it.each(['sourceId','observedAt','validUntil','version'])('rejects missing observer field %s',async field=>{const g=gate(),id=succeeded(g);delete (evidence as any)[field];await expect(g.runObserver(id,'observer')).rejects.toThrow();});
});


