import { logger } from '../utils/logger.js';
import fs from 'fs/promises';
import path from 'path';

const VAULT_PATH = 'C:\\Users\\Cris\\obsidian-vault';

export async function runNewsRadar() {
  logger.info('[News Radar] Starting scheduled news fetch...');
  let summary = '';

  try {
    // 1. Fetch Top 10 HackerNews Stories
    const response = await fetch('https://hacker-news.firebaseio.com/v0/topstories.json');
    if (!response.ok) throw new Error('Failed to fetch HN top stories');
    
    const storyIds = await response.json() as number[];
    const topIds = storyIds.slice(0, 5); // Just grab top 5 to keep it fast
    
    const stories = await Promise.all(
      topIds.map(async (id) => {
        const itemRes = await fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json`);
        return itemRes.json();
      })
    );

    const headlines = stories.map((s: any) => `- [${s.title}](${s.url || `https://news.ycombinator.com/item?id=${s.id}`}) (Score: ${s.score})`).join('\n');
    logger.info('[News Radar] Fetched headlines:\n', headlines);

    // 2. Synthesize Briefing
    const apiKey = process.env.OPENAI_API_KEY;
    if (apiKey) {
      logger.info('[News Radar] Summarizing with LLM...');
      const completion = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: 'gpt-4o-mini',
          messages: [
            { role: 'system', content: 'You are an AI assistant generating a daily briefing. Summarize the following headlines into a concise 2-paragraph tech news brief.' },
            { role: 'user', content: headlines }
          ]
        })
      });

      if (completion.ok) {
        const data = await completion.json();
        summary = data.choices[0].message.content;
      } else {
        summary = `## Tech Headlines\n\n${headlines}`;
      }
    } else {
      summary = `## Tech Headlines\n\n${headlines}`;
    }

    // 3. Save to Obsidian Memory Galaxy
    const dateStr = new Date().toISOString().split('T')[0];
    const logPath = path.join(VAULT_PATH, 'logs', 'daily-briefings');
    await fs.mkdir(logPath, { recursive: true });

    // Write to today.md so the UI can easily read it
    const todayPath = path.join(logPath, 'today.md');
    // Also archive it by date
    const archivePath = path.join(logPath, `${dateStr}.md`);

    const fileContent = `# Daily Briefing: ${dateStr}\n\n${summary}\n\n---\n*Auto-generated by Agentic OS News Radar*`;
    
    await fs.writeFile(todayPath, fileContent, 'utf8');
    await fs.writeFile(archivePath, fileContent, 'utf8');

    logger.info(`[News Radar] Saved daily briefing to ${todayPath}`);
    return { success: true, path: todayPath };

  } catch (err) {
    logger.error('[News Radar] Failed to run news radar:', err);
    return { success: false, error: String(err) };
  }
}
