
import type {
  AgentDefinition, Runtime, ProviderDefinition, RunRecord,
  MemoryScope, MemoryEntry, Artifact, Board, ToolDefinition
} from './types.js';

/* ═══════════════════════════════════════════════════════
   RUNTIMES
   ═══════════════════════════════════════════════════════ */

export const mockRuntimes: Runtime[] = [
  {
    id: "rt-hermes",
    label: "Hermes Runtime",
    adapterType: "hermes-adapter",
    health: { status: "healthy", lastCheck: new Date().toISOString(), latencyMs: 42 },
    supportedModes: ["chat", "task", "workflow"],
    eventProtocol: "sse",
    toolAccessMode: "unrestricted",
  },
  {
    id: "rt-jarvis",
    label: "Jarvis Runtime",
    adapterType: "jarvis-adapter",
    health: { status: "healthy", lastCheck: new Date().toISOString(), latencyMs: 38 },
    supportedModes: ["task", "workflow"],
    eventProtocol: "websocket",
    toolAccessMode: "scoped",
  },
  {
    id: "rt-video",
    label: "Video-Agent Runtime",
    adapterType: "video-adapter",
    health: { status: "healthy", lastCheck: new Date().toISOString(), latencyMs: 5 },
    supportedModes: ["task", "workflow"],
    eventProtocol: "sse",
    toolAccessMode: "scoped",
  },
  {
    id: "rt-heavy-gen",
    label: "Heavy Generation Runtime",
    adapterType: "heavy-gen-adapter",
    health: { status: "healthy", lastCheck: new Date().toISOString(), latencyMs: 25 },
    supportedModes: ["task", "workflow", "chat"],
    eventProtocol: "sse",
    toolAccessMode: "unrestricted",
  },
];

/* ═══════════════════════════════════════════════════════
   AGENTS — 4 agents across 2 runtimes
   ═══════════════════════════════════════════════════════ */

export const mockAgents: AgentDefinition[] = [
  {
    id: "agent-hermes",
    name: "Hermes",
    slug: "hermes",
    avatar: "H",
    color: "#d4a373",
    runtimeId: "rt-hermes",
    kind: "first-class",
    status: "active",
    capabilities: ["code-generation", "reasoning", "planning", "code-review", "memory_galaxy"],
    toolIds: ["tool-code-runner", "tool-browser", "tool-file-system", "tool-memory-read", "tool-memory-append"],
    memoryScopes: ["mem-global", "mem-hermes-agent"],
    providerIds: ["prov-openrouter", "prov-anthropic", "prov-deepseek", "prov-qwen", "prov-xai"],
    defaultBoardId: "board-mission-control",
    visibility: "public",
    description: "Primary reasoning and code-generation agent. Handles complex multi-step tasks with deep planning capabilities.",
    recentActivity: "Completed code review for auth module 12 min ago",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-hermes-ornith",
    name: "Hermes-Ornith",
    slug: "hermes-ornith",
    avatar: "H",
    color: "#d4a373",
    runtimeId: "rt-hermes",
    kind: "first-class",
    status: "active",
    capabilities: ["code-generation", "orchestration", "pipeline-runner"],
    toolIds: ["tool-code-runner", "tool-browser", "tool-file-system"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-ornith"],
    defaultBoardId: "board-mission-control",
    visibility: "public",
    description: "Hermes orchestrator specifically locked to use the local Ornith engine for pipeline execution.",
    recentActivity: "Triggered SCOUT stage 1 min ago",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-jarvis",
    name: "Jarvis",
    slug: "jarvis",
    avatar: "J",
    color: "#63b3ed",
    runtimeId: "rt-jarvis",
    kind: "first-class",
    status: "active",
    capabilities: ["execution", "automation", "deployment", "monitoring"],
    toolIds: ["tool-deploy", "tool-apify", "tool-browser", "tool-speak"],
    memoryScopes: ["mem-global", "mem-jarvis-agent"],
    providerIds: ["prov-openrouter", "prov-ollama", "prov-anthropic", "prov-deepseek", "prov-xai"],
    defaultBoardId: "board-mission-control",
    visibility: "public",
    description: "Execution and automation agent. Uses local Ollama (Gemma 2B) as base heartbeat model, with cloud fallbacks for complex tasks.",
    recentActivity: "Deployed staging build v2.4.1 28 min ago",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-sentinel",
    name: "Sentinel",
    slug: "sentinel",
    avatar: "S",
    color: "#f87171",
    runtimeId: "rt-jarvis",
    kind: "runtime-backed",
    status: "active",
    capabilities: ["monitoring", "alerting", "log-analysis", "anomaly-detection"],
    toolIds: ["tool-log-reader", "tool-metrics"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-ollama", "prov-mistral"],
    defaultBoardId: "board-mission-control",
    visibility: "public",
    description: "System monitoring and alerting agent. Watches runtime health, detects anomalies, and escalates critical issues.",
    recentActivity: "Flagged memory pressure warning 5 min ago",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-video",
    name: "VideoAgent",
    slug: "video-agent",
    avatar: "V",
    color: "#fb923c",
    runtimeId: "rt-video",
    kind: "runtime-backed",
    status: "active",
    capabilities: ["video_generation", "editing"],
    toolIds: ["tool-luma", "tool-kling"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-luma", "prov-kling"],
    defaultBoardId: "board-video",
    visibility: "public",
    description: "AI video generation and editing agent.",
    recentActivity: "Generated 10s clip 2 hours ago",
    createdAt: "2026-06-10T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-gemini-welders-research",
    name: "Welders Researcher",
    slug: "welders-researcher",
    avatar: "W",
    color: "#22c55e",
    runtimeId: "rt-hermes",
    kind: "runtime-backed",
    status: "active",
    capabilities: ["background_interactions", "long_context", "memory_galaxy"],
    toolIds: ["tool-browser", "tool-search"],
    memoryScopes: ["mem-global", "mem-research-board"],
    providerIds: ["prov-gemini", "prov-fugu"],
    defaultBoardId: "board-research",
    visibility: "public",
    description: "Deep research agent for German and Dutch welders job boards using Gemini Interactions API.",
    recentActivity: "No recent activity",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-gemini-email-copy",
    name: "Email Copywriter",
    slug: "email-copywriter",
    avatar: "E",
    color: "#eab308",
    runtimeId: "rt-hermes",
    kind: "runtime-backed",
    status: "active",
    capabilities: ["interactive_interactions", "voice", "memory_galaxy"],
    toolIds: ["tool-browser"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-gemini"],
    defaultBoardId: "board-mission-control",
    visibility: "public",
    description: "Interactive email copywriter for reaching out to welding companies.",
    recentActivity: "No recent activity",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-video-pipeline",
    name: "Video Pipeline",
    slug: "video-pipeline",
    avatar: "VP",
    color: "#a78bfa",
    runtimeId: "rt-video",
    kind: "runtime-backed",
    status: "active",
    capabilities: ["video-scripting", "asset-gathering", "rendering", "publishing"],
    toolIds: ["tool-browser"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-kimi", "prov-minimax"],
    defaultBoardId: "board-builds",
    visibility: "public",
    description: "Video production pipeline agent. Handles scripting, asset gathering, rendering, and publishing.",
    recentActivity: "Rendered intro video for Q3 launch 2 hrs ago",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-fugu",
    name: "Fugu Ultra",
    slug: "fugu",
    avatar: "F",
    color: "#f59e0b",
    runtimeId: "rt-heavy-gen",
    kind: "first-class",
    status: "active",
    capabilities: ["code-generation", "heavy-generation"],
    toolIds: ["tool-code-runner"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-deepseek", "prov-minimax", "prov-qwen", "prov-kimi"],
    defaultBoardId: "board-builds",
    visibility: "public",
    description: "Sakana AI Fugu model. Handles extremely large context codebase generations.",
    recentActivity: "Generated 3,000 line monolith 1 day ago",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-qwythos",
    name: "Qwythos 9B",
    slug: "qwythos",
    avatar: "Q",
    color: "#a78bfa",
    runtimeId: "rt-hermes",
    kind: "first-class",
    status: "active",
    capabilities: ["chat", "reasoning", "local-inference", "orchestration", "pipeline-runner", "workspace-controller"],
    toolIds: ["tool-code-runner", "tool-file-system", "tool-read-config", "tool-write-config", "tool-inspect-workspace", "tool-trigger-build", "tool-read-memory", "tool-write-memory", "tool-speak"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-ollama"],
    defaultBoardId: "board-mission-control",
    visibility: "public",
    description: "Qwythos 9B Abliterated — local LLM via Ollama on port 11434. Uncensored reasoning.",
    recentActivity: "Online via Ollama",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-fusion",
    name: "Fusion",
    slug: "fusion",
    avatar: "Fn",
    color: "#ec4899",
    runtimeId: "rt-heavy-gen",
    kind: "first-class",
    status: "active",
    capabilities: ["simulation", "heavy-generation"],
    toolIds: ["tool-code-runner"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-deepseek", "prov-minimax", "prov-qwen", "prov-kimi"],
    defaultBoardId: "board-experiments",
    visibility: "public",
    description: "OpenRouter Fusion-large model for deep simulations and heavy reasoning.",
    recentActivity: "Ran 15 min simulation yesterday",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-qwable",
    name: "Qwable Coder",
    slug: "qwable-coder",
    avatar: "Qc",
    color: "#3b82f6",
    runtimeId: "rt-hermes",
    kind: "first-class",
    status: "active",
    capabilities: ["code-generation", "ui-generation", "build-preview", "workspace-saving"],
    toolIds: ["tool-code-runner", "tool-file-system"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-qwable"],
    defaultBoardId: "board-builds",
    visibility: "public",
    description: "Local open-source coding model (Qwable 27B) for fast UI, web, and app generation. Runs on Hermes.",
    recentActivity: "Ready for local coding tasks",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-apollo-dialog",
    name: "Apollo Dialog Brain",
    slug: "apollo-dialog",
    avatar: "A",
    color: "#a855f7",
    runtimeId: "rt-hermes",
    kind: "runtime-backed",
    status: "active",
    capabilities: ["voice", "routing"],
    toolIds: ["tool-voice"],
    memoryScopes: ["mem-workspace", "mem-session"],
    providerIds: [],
    defaultBoardId: "board-general",
    visibility: "public",
    description: "Voice Dialog + Intent Routing",
    recentActivity: "Listening for wake-word...",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-apollo-dialog",
    name: "Apollo Dialog Brain",
    slug: "apollo-dialog",
    avatar: "A",
    color: "#a855f7",
    runtimeId: "rt-hermes",
    kind: "runtime-backed",
    status: "active",
    capabilities: ["voice", "routing"],
    toolIds: ["tool-voice"],
    memoryScopes: ["mem-workspace", "mem-session"],
    providerIds: [],
    defaultBoardId: "board-general",
    visibility: "public",
    description: "Voice Dialog + Intent Routing",
    recentActivity: "Listening for wake-word...",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-codex",
    name: "CodeX",
    slug: "codex",
    avatar: "Cx",
    color: "#10b981",
    runtimeId: "rt-hermes",
    kind: "first-class",
    status: "active",
    capabilities: ["code-generation", "code-review", "debugging", "refactoring", "explanation"],
    toolIds: ["tool-code-runner", "tool-file-system", "tool-browser"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-ollama", "prov-openrouter"],
    defaultBoardId: "board-builds",
    visibility: "public",
    description: "Coding assistant — code generation, review, debugging, refactoring. Defaults to local Laguna XS 2.1 via Ollama; falls back to OmniRoute.",
    recentActivity: "Ready for coding tasks",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-magnitude",
    name: "Magnitude",
    slug: "magnitude",
    avatar: "M",
    color: "#f59e0b",
    runtimeId: "rt-jarvis",
    kind: "first-class",
    status: "active",
    capabilities: ["browser_automation", "web_inspection", "dom_analysis", "scraping"],
    toolIds: ["tool-browser"],
    memoryScopes: ["mem-global"],
    providerIds: ["prov-playwright"],
    defaultBoardId: "board-mission-control",
    visibility: "public",
    description: "Browser automation and computer-use agent. Navigates, inspects, and extracts structured web data using Playwright.",
    recentActivity: "Ready for browser tasks",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

/* ──────────────────────────────────────────────────────────
   TOOLS
   ────────────────────────────────────────────────────────── */

export const mockTools: ToolDefinition[] = [
  { id: "tool-code-runner", name: "Code Runner", description: "Executes code in sandboxed environment" },
  { id: "tool-browser", name: "Browser", description: "Headless browser for web interaction" },
  { id: "tool-file-system", name: "File System", description: "Read/write access to workspace files" },
  { id: "tool-deploy", name: "Deploy", description: "Deploy artifacts to staging/production" },
  { id: "tool-apify", name: "Apify Actor", description: "Run Apify actors for scraping workflows" },
  { id: "tool-search", name: "Web Search", description: "Search the web for information" },
  { id: "tool-log-reader", name: "Log Reader", description: "Read and parse system logs" },
  { id: "tool-metrics", name: "Metrics", description: "Query system metrics and health data" },
  { id: "tool-memory-read", name: "Memory Read", description: "Read specific file from Obsidian Memory Galaxy" },
  { id: "tool-memory-append", name: "Memory Append", description: "Append context to specific file in Obsidian Memory Galaxy" },
  { id: "tool-read-config", name: "Read Config", description: "Read agent, pipeline, and provider JSON/TS files" },
  { id: "tool-write-config", name: "Write Config", description: "Write/update agent, pipeline, and provider JSON/TS files" },
  { id: "tool-inspect-workspace", name: "Inspect Workspace", description: "List workspaces, routes, and dashboards" },
  { id: "tool-trigger-build", name: "Trigger Build", description: "Run frontend/backend compilation builds" },
  { id: "tool-read-memory", name: "Read Memory", description: "Read file from Obsidian Vault or Local Workspace" },
  { id: "tool-write-memory", name: "Write Memory", description: "Write file to Obsidian Vault or Local Workspace" },
  { id: "tool-speak", name: "Speak", description: "Reply with voice (TTS via Deepgram)" },
];

/* ═══════════════════════════════════════════════════════
   PROVIDERS — All 7 kinds from the PRD
   ═══════════════════════════════════════════════════════ */

export const mockProviders: ProviderDefinition[] = [
  /* ─── LOCAL RUNNERS ─── */
  {
    id: "prov-ornith",
    name: "Ornith Engine",
    kind: "llm",
    category: "local",
    adapter: "ollama-adapter",
    authScheme: "none",
    status: "connected",
    scopes: ["chat", "completion"],
    description: "The core Ornith local engine used by Agentic OS pipelines.",
    lastActivity: "just now",
    defaultModel: "qwythos:9b",
    models: [
      { id: "qwythos:9b", name: "Qwythos 9B", contextLength: 8192 }
    ],
    usedByAgentDefaults: ["agent-hermes-ornith"],
  },
  {
    id: "prov-ollama",
    name: "Ollama",
    kind: "llm",
    category: "local",
    adapter: "ollama-adapter",
    authScheme: "none",
    status: "connected",
    scopes: ["chat", "completion", "coding"],
    description: "Local Ollama runtime. Hosts coding-specialist and general-purpose models. No API key required. Models run entirely on-device.",
    lastActivity: "just now",
    // Consolidated to the model actually installed in the local Ollama
    // (verified: llama3.2:3b present; laguna-xs-2.1 was NOT) — matches the
    // gateway fallback (OLLAMA_FALLBACK_MODEL || 'llama3.2:3b').
    defaultModel: "llama3.2:3b",
    models: [
      { id: "laguna-xs-2.1", name: "Laguna XS 2.1", displayName: "Laguna XS 2.1 (Local)", contextLength: 32768, inputCost: 0, outputCost: 0 },
      { id: "qwen2.5-coder:14b", name: "Qwen2.5 Coder 14B", displayName: "Qwen2.5-Coder 14B (Local)", contextLength: 32768, inputCost: 0, outputCost: 0 },
      { id: "deepseek-coder-v2:16b", name: "DeepSeek Coder V2 16B", displayName: "DeepSeek-Coder-V2 16B (Local)", contextLength: 163840, inputCost: 0, outputCost: 0 },
      { id: "gemma:2b", name: "Gemma 2B", displayName: "Gemma 2B (Heartbeat)", contextLength: 8192, inputCost: 0, outputCost: 0 },
      { id: "qwythos:9b", name: "Qwythos 9B", displayName: "Qwythos 9B", contextLength: 8192, inputCost: 0, outputCost: 0 },
      { id: "mistral", name: "Mistral 7B", contextLength: 8192, inputCost: 0, outputCost: 0 },
      { id: "qwen2.5", name: "Qwen 2.5", contextLength: 32768, inputCost: 0, outputCost: 0 },
    ],
    usedByAgentDefaults: ["agent-jarvis", "agent-sentinel", "agent-codex"],
  },

  /* ─── REMOTE LLM PROVIDERS ─── */
  {
    id: "prov-fugu",
    name: "Sakana Fugu",
    kind: "llm",
    category: "remote",
    adapter: "openai-adapter",
    authScheme: "key",
    status: "connected",
    scopes: ["chat", "completion", "heavy-generation"],
    description: "Sakana AI Fugu — ultra-fast generation and deep reasoning capabilities via OpenAI-compatible endpoint.",
    lastActivity: "just now",
    defaultModel: "fugu-20260615",
    models: [
      { id: "fugu-20260615", name: "Fugu", contextLength: 128000 },
      { id: "fugu-ultra-20260615", name: "Fugu Ultra", contextLength: 200000 }
    ],
    usedByAgentDefaults: ["agent-gemini-welders-research"]
  },
  {
    id: "prov-openai",
    name: "OpenAI",
    kind: "llm",
    category: "remote",
    adapter: "openai-adapter",
    authScheme: "key",
    status: "needs-auth",
    scopes: ["chat", "completion", "embedding", "tts", "image"],
    description: "OpenAI API provider. Configure an API key before selecting models.",
    lastActivity: "never",
    models: [],
    usedByAgentDefaults: [],
  },
  {
    id: "prov-openrouter",
    name: "OpenRouter",
    kind: "llm",
    category: "remote",
    adapter: "openrouter-adapter",
    authScheme: "key",
    status: "connected",
    scopes: ["chat", "completion"],
    description: "OpenRouter gateway — unified access to 200+ models. Use one key for many providers.",
    lastActivity: "5 min ago",
    defaultModel: "poolside/laguna-s-2.1:free",
    models: [
      { id: "poolside/laguna-s-2.1:free", name: "Poolside Laguna S 2.1 Free" },
      { id: "meituan/longcat-2.0", name: "LongCat 2.0 (Experimental)" },
      { id: "qwen/qwen3.8-max", name: "Qwen 3.8 Max (Experimental)" },
      { id: "deepseek/deepseek-chat", name: "DeepSeek V3" },
      { id: "google/gemini-2.0-flash", name: "Gemini 2.0 Flash" },
    ],
    usedByAgentDefaults: ["agent-hermes", "agent-jarvis"],
  },
  {
    id: "prov-anthropic",
    name: "Anthropic",
    kind: "llm",
    category: "remote",
    adapter: "anthropic-adapter",
    authScheme: "key",
    status: "connected",
    scopes: ["chat", "completion"],
    description: "Anthropic Claude — long-context reasoning, safety, and deep analysis. Claude Sonnet 4 and Opus.",
    lastActivity: "15 min ago",
    defaultModel: "claude-sonnet-4-20250514",
    models: [
      { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4", contextLength: 200000 },
      { id: "claude-opus-4-20250514", name: "Claude Opus 4", contextLength: 200000 },
    ],
    usedByAgentDefaults: ["agent-hermes", "agent-jarvis"],
  },
  {
    id: "prov-deepseek",
    name: "DeepSeek",
    kind: "llm",
    category: "remote",
    adapter: "deepseek-adapter",
    authScheme: "key",
    status: "connected",
    scopes: ["chat", "completion", "reasoning"],
    description: "DeepSeek V4 — optimized for reasoning and coding.",
    lastActivity: "just now",
    defaultModel: "deepseek-v4-flash",
    models: [
      { id: "deepseek-chat", name: "DeepSeek V4 Chat", contextLength: 128000 },
      { id: "deepseek-reasoner", name: "DeepSeek Reasoner", contextLength: 128000 },
      { id: "deepseek-coder", name: "DeepSeek Coder V4", contextLength: 128000 },
      { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", contextLength: 128000 },
      { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", contextLength: 128000 },
    ],
    usedByAgentDefaults: ["agent-hermes", "agent-jarvis"],
  },
  {
    id: "prov-longcat",
    name: "LongCat",
    kind: "llm",
    category: "remote",
    adapter: "openrouter-adapter",
    authScheme: "key",
    status: "connected",
    scopes: ["chat", "completion"],
    description: "Meituan LongCat 2.0 — sparse MoE (48B active / 1.6T total), coding, repo-level changes and agentic workflows. Reached via OpenRouter (provider-confirmed model id: meituan/longcat-2.0).",
    lastActivity: "just now",
    defaultModel: "meituan/longcat-2.0",
    models: [
      { id: "meituan/longcat-2.0", name: "LongCat 2.0", contextLength: 1048756 },
    ],
    usedByAgentDefaults: ["agent-jarvis"],
  },
  {
    id: "prov-minimax",
    name: "MiniMax",
    kind: "llm",
    category: "remote",
    adapter: "minimax-adapter",
    authScheme: "key",
    status: "disconnected",
    scopes: ["chat", "completion", "tts"],
    description: "MiniMax — Hailuo video generation and MiniMax-Text models. Also provides TTS.",
    lastActivity: "never",
    defaultModel: "minimax-text-01",
    models: [
      { id: "minimax-text-01", name: "MiniMax Text-01", contextLength: 1000000 },
      { id: "minimax-video-01", name: "MiniMax Video (Hailuo)" },
    ],
    usedByAgentDefaults: ["agent-video"],
  },
  {
    id: "prov-kimi",
    name: "Kimi / Moonshot",
    kind: "llm",
    category: "remote",
    adapter: "kimi-adapter",
    authScheme: "key",
    status: "disconnected",
    scopes: ["chat", "completion"],
    description: "Kimi by Moonshot AI — K2 model with long context window for deep document analysis.",
    lastActivity: "never",
    defaultModel: "kimi-k2",
    models: [
      { id: "kimi-k2", name: "Kimi K2", contextLength: 128000 },
      { id: "kimi-k2-mini", name: "Kimi K2 Mini", contextLength: 128000 },
    ],
    usedByAgentDefaults: ["agent-video"],
  },
  {
    id: "prov-qwen",
    name: "Alibaba Qwen",
    kind: "llm",
    category: "remote",
    adapter: "qwen-adapter",
    authScheme: "key",
    status: "disconnected",
    scopes: ["chat", "completion"],
    description: "Alibaba Cloud Qwen 3.5 — strong multilingual reasoning and coding via DashScope API.",
    lastActivity: "never",
    defaultModel: "qwen3-5-72b-instruct",
    models: [
      { id: "qwen3-5-72b-instruct", name: "Qwen 3.5 72B Instruct", contextLength: 128000 },
      { id: "qwen3-5-32b-instruct", name: "Qwen 3.5 32B Instruct", contextLength: 128000 },
      { id: "qwen3-5-14b-instruct", name: "Qwen 3.5 14B Instruct", contextLength: 32768 },
      { id: "qwen3-5-coder", name: "Qwen 3.5 Coder", contextLength: 128000 },
    ],
    usedByAgentDefaults: ["agent-hermes"],
  },
  {
    id: "prov-xai",
    name: "xAI / Grok",
    kind: "llm",
    category: "remote",
    adapter: "xai-adapter",
    authScheme: "key",
    status: "disconnected",
    scopes: ["chat", "completion"],
    description: "xAI Grok — cutting-edge reasoning and real-time knowledge via X/Twitter integration.",
    lastActivity: "never",
    defaultModel: "grok-3",
    models: [
      { id: "grok-3", name: "Grok 3", contextLength: 128000 },
      { id: "grok-3-mini", name: "Grok 3 Mini", contextLength: 128000 },
    ],
    usedByAgentDefaults: [],
  },
  {
    id: "prov-mistral",
    name: "Mistral AI",
    kind: "llm",
    category: "remote",
    adapter: "mistral-adapter",
    authScheme: "key",
    status: "connected",
    scopes: ["chat", "completion", "tts"],
    description: "Mistral AI — Mistral Large, Small, and Codestral for code generation. Also provides Voxtral TTS.",
    lastActivity: "just now",
    defaultModel: "mistral-large-latest",
    models: [
      { id: "mistral-large-latest", name: "Mistral Large", contextLength: 128000 },
      { id: "mistral-small-latest", name: "Mistral Small", contextLength: 32000 },
      { id: "codestral-latest", name: "Codestral", contextLength: 256000 },
    ],
    usedByAgentDefaults: ["agent-sentinel"],
  },
  {
    id: "prov-gemini",
    name: "Google Gemini",
    kind: "llm",
    category: "remote",
    adapter: "gemini-adapter",
    authScheme: "key",
    status: "connected",
    scopes: ["chat", "completion", "vision"],
    description: "Google Gemini 2.0 Pro/Flash — multi-modal reasoning with native vision and long context.",
    lastActivity: "just now",
    defaultModel: "gemini-2.0-flash",
    models: [
      { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", contextLength: 1000000 },
      { id: "gemini-2.0-pro-exp", name: "Gemini 2.0 Pro (exp)", contextLength: 2000000 },
      { id: "gemini-2.5-pro-exp", name: "Gemini 2.5 Pro (exp)", contextLength: 1000000 },
    ],
    usedByAgentDefaults: ["agent-athena"],
  },
  {
    id: "prov-perplexity",
    name: "Unavailable Search Provider",
    kind: "llm",
    category: "remote",
    adapter: "perplexity-adapter",
    authScheme: "key",
    status: "disconnected",
    scopes: ["chat", "completion", "search"],
    lastActivity: "never",
    models: [],
    usedByAgentDefaults: [],
  },

  /* ─── INFRASTRUCTURE PROVIDERS ─── */
  {
    id: "prov-mcp-filesystem",
    name: "MCP File System",
    kind: "mcp",
    category: "infra",
    adapter: "mcp-stdio",
    authScheme: "none",
    status: "connected",
    scopes: ["read", "write", "list"],
    description: "MCP server exposing local file system tools.",
    lastActivity: "1 min ago",
  },
  {
    id: "prov-apify",
    name: "Apify Platform",
    kind: "scraper",
    category: "remote",
    adapter: "apify-api",
    authScheme: "token",
    status: "connected",
    scopes: ["run-actor", "list-actors", "get-dataset"],
    description: "Apify integration for web scraping and automation actors.",
    lastActivity: "30 min ago",
  },
  {
    id: "prov-browser-tool",
    name: "Browser Automation",
    kind: "browser",
    category: "infra",
    adapter: "playwright-adapter",
    authScheme: "none",
    status: "connected",
    scopes: ["navigate", "screenshot", "interact"],
    description: "Headless browser for web interaction and testing.",
    lastActivity: "8 min ago",
  },
  {
    id: "prov-internal-api",
    name: "Internal API Gateway",
    kind: "api",
    category: "infra",
    adapter: "rest-adapter",
    authScheme: "oauth",
    status: "needs-auth",
    scopes: ["read", "write"],
    description: "Internal REST API gateway for backend services.",
    lastActivity: "2 hr ago",
    errorMessage: "OAuth token expired, requires re-authentication.",
  },
  {
    id: "prov-storage",
    name: "Cloud Storage",
    kind: "storage",
    category: "infra",
    adapter: "s3-adapter",
    authScheme: "key",
    status: "connected",
    scopes: ["read", "write", "delete"],
    description: "S3-compatible storage backend for artifacts and builds.",
    lastActivity: "5 min ago",
  },
  {
    id: "prov-automation",
    name: "n8n Workflows",
    kind: "automation",
    category: "remote",
    adapter: "n8n-webhook",
    authScheme: "token",
    status: "experimental",
    scopes: ["trigger", "status"],
    description: "n8n workflow automation engine for complex multi-step pipelines.",
    lastActivity: "1 day ago",
  },
  {
    id: "prov-qwable",
    name: "Qwable 27B Coder",
    kind: "llm",
    category: "local",
    adapter: "openai-adapter",
    authScheme: "none",
    status: "connected",
    scopes: [
      "chat",
      "completion",
      "code",
      "ui",
      "preview",
      "workspace"
    ],
    description: "Local open-source coding model based on Qwen 3.6 27B. Runs locally on Apple MLX / Mac Studio.",
    lastActivity: "just now",
    defaultModel: "qwable-27b-coder",
    models: [
      {
        "id": "qwable-27b-coder",
        "name": "Qwable 27B Coder",
        "contextLength": 32768
      }
    ],
    baseUrl: "http://localhost:8642"
  }
];

/* ═══════════════════════════════════════════════════════
   RUNS — All 6 statuses represented
   ═══════════════════════════════════════════════════════ */

export const mockRuns: RunRecord[] = [
  {
    id: "run-001",
    agentId: "agent-hermes",
    sessionId: "sess-1",
    workspaceId: "ws-1",
    mode: "task",
    status: "running",
    input: "Analyze auth module for security vulnerabilities and generate a fix proposal.",
    logs: ["[00:00] Started security analysis...", "[00:12] Scanning dependencies...", "[00:24] Found 2 potential issues..."],
    events: [],
    linkedArtifacts: [],
    durationMs: 45000,
    createdAt: new Date(Date.now() - 45000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "run-002",
    agentId: "agent-jarvis",
    sessionId: "sess-2",
    workspaceId: "ws-1",
    mode: "workflow",
    status: "running",
    input: "Deploy staging build v2.4.1 with database migration.",
    logs: ["[00:00] Building artifacts...", "[00:30] Running migrations...", "[01:02] Deploying to staging..."],
    events: [],
    linkedArtifacts: ["art-staging-build"],
    durationMs: 92000,
    createdAt: new Date(Date.now() - 92000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "run-003",
    agentId: "agent-athena",
    sessionId: "sess-3",
    workspaceId: "ws-1",
    mode: "task",
    status: "queued",
    input: "Research competitive landscape for AI agent frameworks Q3 2026.",
    logs: [],
    events: [],
    linkedArtifacts: [],
    createdAt: new Date(Date.now() - 120000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "run-004",
    agentId: "agent-hermes",
    sessionId: "sess-4",
    workspaceId: "ws-1",
    mode: "chat",
    status: "waiting",
    input: "Review the proposed API schema changes. Waiting for user confirmation.",
    output: "I've identified 3 breaking changes in the proposed schema. Please confirm which changes to proceed with:\n1. Rename `userId` → `accountId`\n2. Remove deprecated `legacyAuth` field\n3. Add required `scopeId` parameter",
    logs: ["[00:00] Analyzing schema diff...", "[00:08] Found 3 breaking changes.", "[00:09] Awaiting user input."],
    events: [],
    linkedArtifacts: ["art-schema-diff"],
    createdAt: new Date(Date.now() - 300000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "run-005",
    agentId: "agent-sentinel",
    sessionId: "sess-5",
    workspaceId: "ws-1",
    mode: "task",
    status: "failed",
    input: "Monitor production logs for the last 24 hours and flag anomalies.",
    output: "Error: Connection to log aggregator timed out after 30s.",
    logs: ["[00:00] Connecting to log aggregator...", "[00:30] Connection timeout.", "[00:30] Retrying...", "[01:00] Final timeout. Task failed."],
    events: [],
    linkedArtifacts: [],
    errorMessage: "Connection to log aggregator timed out after 30s.",
    durationMs: 60000,
    createdAt: new Date(Date.now() - 600000).toISOString(),
    updatedAt: new Date(Date.now() - 540000).toISOString(),
  },
  {
    id: "run-006",
    agentId: "agent-hermes",
    sessionId: "sess-6",
    workspaceId: "ws-1",
    mode: "task",
    status: "completed",
    input: "Generate unit tests for the payment processing module.",
    output: "Created 14 unit tests covering all public methods. 100% branch coverage achieved.",
    logs: ["[00:00] Analyzing payment module...", "[00:15] Generating test cases...", "[00:42] Writing test file...", "[00:48] All tests passing."],
    events: [],
    linkedArtifacts: ["art-unit-tests"],
    durationMs: 48000,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3552000).toISOString(),
  },
  {
    id: "run-007",
    agentId: "agent-jarvis",
    sessionId: "sess-7",
    workspaceId: "ws-1",
    mode: "workflow",
    status: "completed",
    input: "Run full E2E test suite against staging.",
    output: "All 47 E2E tests passed. Average test duration: 1.2s.",
    logs: ["[00:00] Starting E2E suite...", "[02:30] 47/47 tests passed."],
    events: [],
    linkedArtifacts: ["art-e2e-report"],
    durationMs: 150000,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7050000).toISOString(),
  },
  {
    id: "run-008",
    agentId: "agent-athena",
    sessionId: "sess-8",
    workspaceId: "ws-1",
    mode: "task",
    status: "archived",
    input: "Summarize all findings from last week's research sprint.",
    output: "Weekly summary generated with 12 key findings across 4 domains.",
    logs: ["[00:00] Aggregating research entries...", "[00:20] Generating summary..."],
    events: [],
    linkedArtifacts: ["art-weekly-summary"],
    durationMs: 30000,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86370000).toISOString(),
  },
  {
    id: "run-009",
    agentId: "agent-sentinel",
    sessionId: "sess-9",
    workspaceId: "ws-1",
    mode: "task",
    status: "queued",
    input: "Scan infrastructure for expired SSL certificates.",
    logs: [],
    events: [],
    linkedArtifacts: [],
    createdAt: new Date(Date.now() - 5000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

/* ═══════════════════════════════════════════════════════
   MEMORY SCOPES — All 5 types from the PRD
   ═══════════════════════════════════════════════════════ */

export const mockMemoryScopes: MemoryScope[] = [
  {
    id: "mem-global",
    workspaceId: "ws-1",
    name: "Global Context",
    type: "global",
    summary: "System-wide persistent facts, decisions, and project context shared across all agents and sessions.",
    tags: ["system", "core", "persistent"],
    permissions: ["read", "write"],
    entryCount: 24,
    lastUpdated: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: "mem-workspace-main",
    workspaceId: "ws-1",
    name: "Main Workspace",
    type: "board",
    summary: "Workspace-level context for the primary development workspace including project goals and constraints.",
    tags: ["workspace", "project"],
    permissions: ["read", "write"],
    entryCount: 18,
    lastUpdated: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: "mem-hermes-agent",
    workspaceId: "ws-1",
    name: "Hermes Agent Memory",
    type: "agent",
    summary: "Hermes-specific learned preferences, code patterns, and accumulated project knowledge.",
    tags: ["agent", "hermes", "code-patterns"],
    permissions: ["read", "write"],
    entryCount: 42,
    lastUpdated: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: "mem-jarvis-agent",
    workspaceId: "ws-1",
    name: "Jarvis Agent Memory",
    type: "agent",
    summary: "Jarvis-specific deployment history, infrastructure state, and automation playbooks.",
    tags: ["agent", "jarvis", "devops"],
    permissions: ["read", "write"],
    entryCount: 31,
    lastUpdated: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "mem-session-current",
    workspaceId: "ws-1",
    name: "Current Session",
    type: "session",
    summary: "Short-term context for the current working session, including recent decisions and open threads.",
    tags: ["session", "ephemeral"],
    permissions: ["read", "write"],
    entryCount: 8,
    lastUpdated: new Date(Date.now() - 60000).toISOString(),
  },
  {
    id: "mem-research-board",
    workspaceId: "ws-1",
    name: "Research Board Context",
    type: "board",
    summary: "Research findings, open questions, and decision logs for the research board.",
    tags: ["research", "findings"],
    permissions: ["read", "write"],
    entryCount: 15,
    lastUpdated: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "mem-task-auth-review",
    workspaceId: "ws-1",
    name: "Auth Review Task",
    type: "task",
    summary: "Task-scoped memory for the ongoing authentication module security review.",
    tags: ["task", "security", "auth"],
    permissions: ["read"],
    entryCount: 6,
    lastUpdated: new Date(Date.now() - 45000).toISOString(),
  },
  {
    id: "mem-workspace",
    workspaceId: "ws-1",
    name: "Workspace Context",
    type: "workspace",
    summary: "High-level workspace context for Hermes operations.",
    tags: ["workspace"],
    permissions: ["read", "write"],
    entryCount: 2,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "mem-session",
    workspaceId: "ws-1",
    name: "Session Context",
    type: "session",
    summary: "Ephemeral session memory.",
    tags: ["session"],
    permissions: ["read", "write"],
    entryCount: 1,
    lastUpdated: new Date().toISOString(),
  },
];

/* ═══════════════════════════════════════════════════════
   MEMORY ENTRIES
   ═══════════════════════════════════════════════════════ */

export const mockMemoryEntries: MemoryEntry[] = [
  {
    id: "entry-001",
    scopeId: "mem-global",
    kind: "fact",
    title: "Project Architecture",
    content: "The system uses a four-layer architecture: UI Shell → OS Services → Agent Runtimes → Execution Providers.",
    links: ["board-mission-control"],
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
  },
  {
    id: "entry-002",
    scopeId: "mem-global",
    kind: "decision",
    title: "Runtime Adapter Contract",
    content: "All runtimes must implement the RuntimeAdapter interface. No direct coupling between the UI shell and runtime internals.",
    links: ["rt-hermes", "rt-jarvis"],
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-15T00:00:00Z",
  },
  {
    id: "entry-003",
    scopeId: "mem-hermes-agent",
    kind: "note",
    title: "Q3 Competitive Analysis Draft",
    content: "We need to expand the section on new startup entrants and their pricing models.",
    createdAt: "2026-06-25T11:00:00Z",
    updatedAt: "2026-06-25T11:45:00Z",
  },
  {
    id: "mem-ent-1006",
    scopeId: "mem-workspace",
    kind: "fact",
    title: "Project Phoenix Launch",
    content: "Project Phoenix is targeted for Q4 2026. All agents must prioritize Phoenix issues.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mem-ent-1007",
    scopeId: "mem-session",
    kind: "note",
    title: "Current Apollo Context",
    content: "User requested Apollo Wall mode implementation.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "entry-004",
    scopeId: "mem-session-current",
    kind: "conversation",
    title: "Current Focus: Auth Module Review",
    content: "Currently reviewing the auth module for security vulnerabilities. Hermes is running analysis, awaiting results.",
    sourceRunId: "run-001",
    createdAt: new Date(Date.now() - 45000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "entry-005",
    scopeId: "mem-research-board",
    kind: "summary",
    title: "Q3 Competitive Analysis Draft",
    content: "Initial findings on 6 competitor agent frameworks. Key differentiator: unified runtime adapter model.",
    sourceRunId: "run-008",
    links: ["art-weekly-summary"],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86370000).toISOString(),
  },
];

/* ═══════════════════════════════════════════════════════
   ARTIFACTS — All 5 statuses represented
   ═══════════════════════════════════════════════════════ */

export const mockArtifacts: Artifact[] = [
  {
    id: "art-schema-diff",
    type: "document",
    title: "API Schema Change Proposal",
    preview: "Proposed 3 breaking changes to the REST API schema affecting auth and user endpoints.",
    sourceRunId: "run-004",
    linkedAgentId: "agent-hermes",
    version: "1.2",
    status: "review",
  },
  {
    id: "art-unit-tests",
    type: "code",
    title: "Payment Module Unit Tests",
    preview: "14 unit tests covering all public methods in the payment processing module. 100% branch coverage.",
    sourceRunId: "run-006",
    linkedAgentId: "agent-hermes",
    version: "1.0",
    status: "done",
  },
  {
    id: "art-staging-build",
    type: "build",
    title: "Staging Build v2.4.1",
    preview: "Production-ready build with database migration scripts. Includes auth module updates.",
    sourceRunId: "run-002",
    linkedAgentId: "agent-jarvis",
    version: "2.4.1",
    status: "active",
  },
  {
    id: "art-e2e-report",
    type: "report",
    title: "E2E Test Report",
    preview: "Full end-to-end test results: 47/47 tests passed across 12 feature areas.",
    sourceRunId: "run-007",
    linkedAgentId: "agent-jarvis",
    version: "1.0",
    status: "done",
  },
  {
    id: "art-weekly-summary",
    type: "document",
    title: "Weekly Research Summary",
    preview: "12 key findings from last week's research sprint across competitive analysis, market sizing, and tech evaluation.",
    sourceRunId: "run-008",
    linkedAgentId: "agent-athena",
    linkedBoardId: "board-research",
    version: "1.0",
    status: "archived",
  },
  {
    id: "art-security-draft",
    type: "report",
    title: "Security Audit Draft",
    preview: "Preliminary findings from the auth module security scan. 2 potential vulnerabilities identified.",
    sourceRunId: "run-001",
    linkedAgentId: "agent-hermes",
    version: "0.1",
    status: "draft",
  },
];

/* ═══════════════════════════════════════════════════════
   BOARDS — All 6 board definitions from the PRD
   ═══════════════════════════════════════════════════════ */

export const mockBoards: Board[] = [
  {
    id: "board-mission-control",
    name: "Mission Control",
    purpose: "Global cockpit for active agents, runs, provider health, and system alerts.",
    color: "#d4a373",
    icon: "LayoutDashboard",
    cardTypes: ["agent", "run", "provider", "alert"],
    filters: {},
    layoutMode: "board",
  },
  {
    id: "board-welders",
    name: "Workers Placement Leads",
    purpose: "Pipeline tracking for welder and electrician recruitment in DE/NL.",
    color: "#fb923c",
    icon: "Briefcase",
    cardTypes: ["lead"],
    filters: {},
    layoutMode: "kanban",
  },
  {
    id: "board-sales",
    name: "Agentic OS CRM Sales",
    purpose: "Pipeline tracking for B2B sales of Agentic OS and Muncade CRM.",
    color: "#38bdf8",
    icon: "BadgeDollarSign",
    cardTypes: ["lead"],
    filters: {},
    layoutMode: "kanban",
  },
  {
    id: "board-agents",
    name: "Agent Registry",
    purpose: "Visual roster of all agents, runtimes, and capabilities.",
    color: "#63b3ed",
    icon: "Users",
    cardTypes: ["agent"],
    filters: {},
    layoutMode: "gallery",
  },
  {
    id: "board-research",
    name: "Research",
    purpose: "Structured deep-work board for research tasks, questions, findings, and decisions.",
    color: "#c084fc",
    icon: "BookOpen",
    cardTypes: ["run", "artifact", "memory"],
    filters: {},
    layoutMode: "board",
  },
  {
    id: "board-builds",
    name: "Builds & Artifacts",
    purpose: "Generated applications, experiments, artifacts, prototypes, and outputs.",
    color: "#34d399",
    icon: "Package",
    cardTypes: ["artifact", "build"],
    filters: {},
    layoutMode: "kanban",
  },
  {
    id: "board-integrations",
    name: "Integrations",
    purpose: "Provider registry and connection management for all external services.",
    color: "#fbbf24",
    icon: "HardDrive",
    cardTypes: ["provider"],
    filters: {},
    layoutMode: "board",
  },
  {
    id: "board-experiments",
    name: "Experiments",
    purpose: "Sandboxed space for testing new agents, workflows, and model configurations.",
    color: "#f87171",
    icon: "FlaskConical",
    cardTypes: ["run", "artifact", "agent"],
    filters: {},
    layoutMode: "board",
  },
  {
    id: "board-scraping",
    name: "Web Scraping Pipeline",
    purpose: "Dedicated workspace for Apify extractions, actor runs, and dataset reviews.",
    color: "#10b981", // Emerald green
    icon: "Search",
    cardTypes: ["run", "artifact", "provider"],
    filters: { providerId: "prov-apify" },
    layoutMode: "kanban",
  },
];

/* ═══════════════════════════════════════════════════════
   HELPER: find agent by id
   ═══════════════════════════════════════════════════════ */

export function getAgentById(id: string): AgentDefinition | undefined {
  return mockAgents.find(a => a.id === id);
}

export function getProviderById(id: string): ProviderDefinition | undefined {
  return mockProviders.find(p => p.id === id);
}

export function getRunById(id: string): RunRecord | undefined {
  return mockRuns.find(r => r.id === id);
}

export function getMemoryScopeById(id: string): MemoryScope | undefined {
  return mockMemoryScopes.find(m => m.id === id);
}

export function getArtifactById(id: string): Artifact | undefined {
  return mockArtifacts.find(a => a.id === id);
}


