/**
 * WorkspaceIndexer V1 — bounded, project-scoped evidence retrieval.
 *
 * Architecture (per docs/proposals/workspace-indexer-audit.md):
 *   - Local-first, deterministic, model-independent.
 *   - SQLite FTS5 for ranked TEXT retrieval (same proven pattern as
 *     memory_fts in services/memory/store.ts).
 *   - Live in-process literal scan for EXACT mode (zero-staleness,
 *     authoritative ground truth — no shell-outs, no findstr/grep).
 *   - No embeddings, no AST, no vector DB (audit §3).
 *
 * Security contract:
 *   - The authoritative workspace root comes from workspaceStore
 *     (getWorkspaceRoot / project.workspacePath) — never from arbitrary
 *     API input.
 *   - Every scanned path is verified inside the workspace root
 *     (isPathInsideWorkspace).
 *   - Ignore rules exclude node_modules/.git/dist/build/runtime data/
 *     secret files/binaries; nothing outside the workspace is touched.
 *   - Indexing is local filesystem processing only — zero cloud-model
 *     calls are generated by indexing or search (privacy-policy aware by
 *     construction; P16 proves it at runtime).
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { rawDb, sqliteDbPath } from '../db/index.js';
import { getWorkspaceRoot, isPathInsideWorkspace } from './workspaceStore.js';
import { projectsStore } from './projectsStore.js';
import { logger } from '../utils/logger.js';

/* ── Budgets (evidence protection) ─────────────────────────────── */
export const WI_MAX_RESULTS = 25;
export const WI_MAX_SNIPPET_CHARS = 240;
export const WI_MAX_AGGREGATE_CHARS = 8000;
export const WI_MAX_FILE_SIZE = 512 * 1024; // per-file indexing cap
export const WI_SEARCH_TIMEOUT_MS = 5000;
export const WI_MAX_FILES_SCANNED = 60000;
export const WI_MAX_SYMBOLS = 50;

/* ── Ignore policy (P4) ────────────────────────────────────────── */
const IGNORE_DIRS = new Set([
  'node_modules', '.git', 'dist', 'dist-electron', 'build', '.agentos',
  '.agentic', '.hermes', '.claude', 'coverage', '.venv', 'venv',
  '__pycache__', '.cache', '.turbo', 'target', '.next', '.nuxt', 'out',
  '.parcel-cache', '.serverless', '.idea', '.vscode', '.docusaurus',
  'release', 'tmp', '.tmp',
]);
const IGNORE_FILE_PATTERNS = [
  /^\.env(\..*)?$/, /^\.env$/, /^\.DS_Store$/, /^Thumbs\.db$/,
  /^package-lock\.json$/, /^yarn\.lock$/, /^pnpm-lock\.(yaml|yml)$/,
  /^npm-shrinkwrap\.json$/, /^\.eslintcache$/, /^tsconfig\.tsbuildinfo$/,
  /^.*\.(pem|key|p12|pfx|crt|pub)$/i, /^credentials.*$/i, /^secrets.*$/i,
  /^.*_key\.json$/i,
];
const IGNORE_EXT = new Set([
  '.db', '.sqlite', '.sqlite3', '.map', '.lock', '.min.js', '.bundle.js',
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.ico', '.svg', '.woff',
  '.woff2', '.ttf', '.eot', '.pdf', '.zip', '.gz', '.tar', '.7z', '.rar',
  '.exe', '.dll', '.so', '.dylib', '.class', '.jar', '.pyc', '.mp3',
  '.mp4', '.wav', '.mov', '.avi', '.wasm', '.node', '.obj', '.o', '.a',
  '.bin', '.dat', '.log', '.tsbuildinfo',
]);
/** Text extensions actually useful to AgenticOS (source/config/docs). */
const TEXT_EXT = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.json', '.md', '.txt',
  '.css', '.html', '.htm', '.yaml', '.yml', '.toml', '.xml', '.env.example',
  '.sh', '.bat', '.ps1', '.py', '.sql', '.prisma', '.graphql', '.vue',
  '.svelte', '.astro', '.ini', '.cfg', '.conf', '.properties', '.gitignore',
  '.editorconfig', '.prettierrc', '.eslintrc', '.npmrc', '.nvmrc',
]);

export type WorkspaceSearchMode = 'auto' | 'exact' | 'text';

export interface WorkspaceIndexStats {
  workspaceRoot: string;
  workspaceId: string;
  projectId?: string | null;
  filesScanned: number;
  filesIndexed: number;
  filesUpdated: number;
  filesDeleted: number;
  filesSkipped: number;
  filesRejected: number;
  filesTotal: number;
  durationMs: number;
  startedAt: string;
  completedAt: string;
  error?: string;
}

export interface WorkspaceSearchHit {
  relPath: string;       // workspace-relative POSIX path
  absPath: string;       // resolved absolute path (internal truth)
  mode: 'exact' | 'fts';
  line?: number;         // 1-based; real when resolved
  lineResolved: boolean; // false when line resolution is unavailable
  snippet: string;       // bounded
  score?: number;        // bm25 when mode=fts
  workspaceId: string;
}

export interface WorkspaceSearchResponse {
  query: string;
  mode: WorkspaceSearchMode;
  chosenMode: 'exact' | 'fts';
  workspaceRoot: string;
  workspaceId: string;
  projectId?: string | null;
  results: WorkspaceSearchHit[];
  total: number;
  truncated: boolean;
  durationMs: number;
  error?: string;
}

/* ── Workspace identity ────────────────────────────────────────── */
export function normalizeWorkspaceId(root: string): string {
  const norm = root.replace(/\\/g, '/').replace(/\/+$/, '');
  return process.platform === 'win32' ? norm.toLowerCase() : norm;
}

/** Authoritative workspace context: project association wins, else canonical root. */
export function resolveWorkspaceContext(projectId?: string | null, rootOverride?: string):
  { workspaceRoot: string; workspaceId: string; projectId?: string | null; error?: string } {
  let root = '';
  let resolvedProjectId: string | null = null;

  if (projectId) {
    const project = projectsStore.getProject(projectId);
    if (!project) {
      return { workspaceRoot: '', workspaceId: '', projectId, error: `Unknown project: ${projectId}` };
    }
    resolvedProjectId = projectId;
    root = (project.workspacePath && project.workspacePath.trim()) || getWorkspaceRoot();
  } else if (rootOverride) {
    root = rootOverride;
  } else {
    root = getWorkspaceRoot();
  }

  if (!root || !fs.existsSync(root)) {
    return { workspaceRoot: '', workspaceId: '', projectId: resolvedProjectId, error: 'No workspace selected/configured.' };
  }
  return { workspaceRoot: root, workspaceId: normalizeWorkspaceId(root), projectId: resolvedProjectId };
}

/* ── DDL (idempotent, established rawDb pattern) ──────────────── */
const DDL = `
CREATE TABLE IF NOT EXISTS workspace_index_files (
  workspace_id TEXT NOT NULL,
  rel_path TEXT NOT NULL,
  abs_path TEXT NOT NULL,
  ext TEXT NOT NULL DEFAULT '',
  size INTEGER NOT NULL DEFAULT 0,
  mtime_ms INTEGER NOT NULL DEFAULT 0,
  content_hash TEXT NOT NULL DEFAULT '',
  indexed_at TEXT NOT NULL,
  PRIMARY KEY (workspace_id, rel_path)
);
CREATE VIRTUAL TABLE IF NOT EXISTS workspace_index_fts USING fts5(
  workspace_id UNINDEXED, rel_path UNINDEXED, symbols, content,
  tokenize = 'unicode61'
);
CREATE INDEX IF NOT EXISTS idx_ws_index_mtime ON workspace_index_files(workspace_id, mtime_ms);
`;

let initialized = false;
export function ensureWorkspaceIndexTables(): void {
  if (initialized) return;
  rawDb.exec(DDL);
  initialized = true;
}

/* ── Runtime data dir (the SQLite DB + legacy JSON stores live here) ──
   Always skipped: runtime data is not source evidence and may contain
   operational noise (never secrets — secret files are ignored by name). */
const RUNTIME_DATA_DIR = path.resolve(path.dirname(sqliteDbPath));

/* ── Ignore helpers ────────────────────────────────────────────── */
function isIgnoredName(name: string): boolean {
  if (IGNORE_DIRS.has(name)) return true;
  if (IGNORE_EXT.has(path.extname(name).toLowerCase())) return true;
  return IGNORE_FILE_PATTERNS.some((re) => re.test(name));
}

function isLikelyBinary(buf: Buffer): boolean {
  // NUL byte in the first 8KB is a strong text/binary discriminator.
  const probe = buf.subarray(0, 8192);
  return probe.includes(0);
}

/* ── Symbols (light heuristic — no AST, per audit §4) ─────────── */
const SYMBOL_RE = /(?:export\s+)?(?:async\s+)?(?:function|class|interface|type|const|let|var|enum)\s+([A-Za-z_$][\w$]*)/g;
function extractSymbols(content: string): string {
  const found: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = SYMBOL_RE.exec(content)) !== null && found.length < WI_MAX_SYMBOLS) {
    found.push(m[1]);
  }
  return found.join(' ');
}

/* ── Content read (text-only, capped, binary-safe) ────────────── */
function readIndexableContent(absPath: string): { content: string; rejected: boolean; reason?: string } {
  let stat: fs.Stats;
  try {
    stat = fs.statSync(absPath);
  } catch {
    return { content: '', rejected: true, reason: 'unreadable' };
  }
  if (!stat.isFile()) return { content: '', rejected: true, reason: 'not-a-file' };
  if (stat.size > WI_MAX_FILE_SIZE) return { content: '', rejected: true, reason: 'oversize' };
  let buf: Buffer;
  try {
    buf = fs.readFileSync(absPath);
  } catch {
    return { content: '', rejected: true, reason: 'unreadable' };
  }
  if (isLikelyBinary(buf)) return { content: '', rejected: true, reason: 'binary' };
  // Malformed UTF-8 decodes with U+FFFD replacement (documented behavior).
  return { content: buf.toString('utf-8'), rejected: false };
}

/* ── Core walker (deterministic, bounded, cancellable) ────────── */
interface CandidateFile {
  absPath: string;
  relPath: string; // POSIX
  ext: string;
  size: number;
  mtimeMs: number;
}

function walkWorkspace(root: string, signal?: AbortSignal): { candidates: CandidateFile[]; scanned: number; rejected: number; truncated: boolean } {
  const candidates: CandidateFile[] = [];
  let scanned = 0;
  let rejected = 0;
  let truncated = false;
  const stack: string[] = [root];

  while (stack.length > 0) {
    if (signal?.aborted) break;
    if (scanned > WI_MAX_FILES_SCANNED) { truncated = true; break; }
    const dir = stack.pop()!;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      rejected += 1; // unreadable dir → rejected, continue
      continue;
    }
    for (const entry of entries) {
      if (signal?.aborted) break;
      if (scanned++ > WI_MAX_FILES_SCANNED) { truncated = true; break; }
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!isIgnoredName(entry.name) && path.resolve(full) !== RUNTIME_DATA_DIR) stack.push(full);
      } else if (entry.isFile()) {
        if (isIgnoredName(entry.name)) { rejected += 1; continue; }
        const rel = path.relative(root, full);
        const relPosix = rel.replace(/\\/g, '/');
        if (relPosix.startsWith('..') || path.isAbsolute(relPosix)) { rejected += 1; continue; } // boundary guard
        let stat: fs.Stats;
        try {
          stat = fs.statSync(full);
        } catch {
          rejected += 1;
          continue;
        }
        candidates.push({
          absPath: full,
          relPath: relPosix,
          ext: path.extname(entry.name).toLowerCase(),
          size: stat.size,
          mtimeMs: Math.floor(stat.mtimeMs),
        });
      }
    }
    if (signal?.aborted) break;
  }
  return { candidates, scanned, rejected, truncated };
}

/* ── Indexing (initial + incremental) ─────────────────────────── */
export function indexWorkspace(opts: { projectId?: string | null; signal?: AbortSignal; rootOverride?: string } = {}):
  WorkspaceIndexStats {
  ensureWorkspaceIndexTables();
  const startedAt = new Date().toISOString();
  const t0 = Date.now();
  const ctx = resolveWorkspaceContext(opts.projectId, opts.rootOverride);
  if (ctx.error || !ctx.workspaceRoot) {
    logger.warn('[WorkspaceIndex] workspace.index.failed', { projectId: opts.projectId ?? null, error: ctx.error });
    return {
      workspaceRoot: '', workspaceId: '', projectId: opts.projectId ?? null,
      filesScanned: 0, filesIndexed: 0, filesUpdated: 0, filesDeleted: 0,
      filesSkipped: 0, filesRejected: 0, filesTotal: 0,
      durationMs: Date.now() - t0, startedAt, completedAt: new Date().toISOString(),
      error: ctx.error,
    };
  }
  const { workspaceRoot, workspaceId, projectId } = ctx;
  const signal = opts.signal;

  logger.info('[WorkspaceIndex] workspace.index.started', {
    workspaceId, projectId: projectId ?? null, root: workspaceRoot,
  });

  const walk = walkWorkspace(workspaceRoot, signal);
  const seen = new Set<string>();
  const existing = new Map<string, { mtime_ms: number; size: number; content_hash: string }>();
  const rows = rawDb.prepare('SELECT rel_path, mtime_ms, size, content_hash FROM workspace_index_files WHERE workspace_id = ?')
    .all(workspaceId) as Array<{ rel_path: string; mtime_ms: number; size: number; content_hash: string }>;
  for (const r of rows) existing.set(r.rel_path, r);

  let filesIndexed = 0;
  let filesUpdated = 0;
  let filesSkipped = 0;
  let filesRejected = walk.rejected;

  const upsertFile = rawDb.transaction((c: CandidateFile, content: string) => {
    const hash = crypto.createHash('sha1').update(content, 'utf-8').digest('hex');
    rawDb.prepare(`INSERT INTO workspace_index_files (workspace_id, rel_path, abs_path, ext, size, mtime_ms, content_hash, indexed_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(workspace_id, rel_path) DO UPDATE SET abs_path=excluded.abs_path, ext=excluded.ext,
        size=excluded.size, mtime_ms=excluded.mtime_ms, content_hash=excluded.content_hash, indexed_at=excluded.indexed_at`)
      .run(workspaceId, c.relPath, c.absPath, c.ext, c.size, c.mtimeMs, hash, new Date().toISOString());
    rawDb.prepare('DELETE FROM workspace_index_fts WHERE workspace_id = ? AND rel_path = ?').run(workspaceId, c.relPath);
    rawDb.prepare('INSERT INTO workspace_index_fts (workspace_id, rel_path, symbols, content) VALUES (?, ?, ?, ?)')
      .run(workspaceId, c.relPath, extractSymbols(content), content);
  });

  for (const c of walk.candidates) {
    if (signal?.aborted) break;
    seen.add(c.relPath);
    const prev = existing.get(c.relPath);
    if (prev && prev.mtime_ms === c.mtimeMs && prev.size === c.size) {
      filesSkipped += 1;
      continue;
    }
    const read = readIndexableContent(c.absPath);
    if (read.rejected) {
      filesRejected += 1;
      continue;
    }
    if (prev) {
      filesUpdated += 1;
    } else {
      filesIndexed += 1;
    }
    upsertFile(c, read.content);
  }

  // Deleted files: rows in the index not present on disk.
  let filesDeleted = 0;
  const deleteFile = rawDb.transaction((relPath: string) => {
    rawDb.prepare('DELETE FROM workspace_index_files WHERE workspace_id = ? AND rel_path = ?').run(workspaceId, relPath);
    rawDb.prepare('DELETE FROM workspace_index_fts WHERE workspace_id = ? AND rel_path = ?').run(workspaceId, relPath);
  });
  for (const relPath of existing.keys()) {
    if (!seen.has(relPath)) {
      deleteFile(relPath);
      filesDeleted += 1;
    }
  }

  const filesTotal = (rawDb.prepare('SELECT COUNT(*) AS n FROM workspace_index_files WHERE workspace_id = ?').get(workspaceId) as { n: number }).n;
  const durationMs = Date.now() - t0;
  logger.info('[WorkspaceIndex] workspace.index.completed', {
    workspaceId, projectId: projectId ?? null, filesScanned: walk.scanned, filesIndexed,
    filesUpdated, filesDeleted, filesSkipped, filesRejected, filesTotal, durationMs,
    truncated: walk.truncated, cancelled: signal?.aborted ?? false,
  });
  return {
    workspaceRoot, workspaceId, projectId: projectId ?? null,
    filesScanned: walk.scanned, filesIndexed, filesUpdated, filesDeleted, filesSkipped,
    filesRejected, filesTotal, durationMs, startedAt, completedAt: new Date().toISOString(),
  };
}

export function clearWorkspaceIndex(opts: { projectId?: string | null; rootOverride?: string } = {}): { ok: boolean; workspaceId?: string; error?: string } {
  ensureWorkspaceIndexTables();
  const ctx = resolveWorkspaceContext(opts.projectId, opts.rootOverride);
  if (ctx.error || !ctx.workspaceId) return { ok: false, error: ctx.error ?? 'No workspace selected/configured.' };
  rawDb.transaction(() => {
    rawDb.prepare('DELETE FROM workspace_index_fts WHERE workspace_id = ?').run(ctx.workspaceId!);
    rawDb.prepare('DELETE FROM workspace_index_files WHERE workspace_id = ?').run(ctx.workspaceId!);
  })();
  logger.info('[WorkspaceIndex] workspace.index.cleared', { workspaceId: ctx.workspaceId, projectId: opts.projectId ?? null });
  return { ok: true, workspaceId: ctx.workspaceId };
}

export function getIndexStatus(opts: { projectId?: string | null; rootOverride?: string } = {}): {
  workspaceRoot: string; workspaceId: string; projectId?: string | null;
  filesTotal: number; lastIndexedAt: string | null; error?: string;
} {
  ensureWorkspaceIndexTables();
  const ctx = resolveWorkspaceContext(opts.projectId, opts.rootOverride);
  if (ctx.error || !ctx.workspaceId) {
    return { workspaceRoot: '', workspaceId: '', projectId: opts.projectId ?? null, filesTotal: 0, lastIndexedAt: null, error: ctx.error };
  }
  const row = rawDb.prepare('SELECT COUNT(*) AS n, MAX(indexed_at) AS last FROM workspace_index_files WHERE workspace_id = ?')
    .get(ctx.workspaceId) as { n: number; last: string | null };
  return {
    workspaceRoot: ctx.workspaceRoot, workspaceId: ctx.workspaceId, projectId: ctx.projectId ?? null,
    filesTotal: row.n, lastIndexedAt: row.last,
  };
}

/* ── Retrieval ────────────────────────────────────────────────── */
function isExactPreferredQuery(query: string): boolean {
  // Single token without spaces and without regex metacharacters → cheap
  // live literal scan is the correct, cheapest mechanism (AUTO mode).
  if (/\s/.test(query)) return false;
  if (/[.*+?^${}()|[\]\\]/.test(query)) return false;
  return query.length > 0;
}

function readFileLines(absPath: string): string[] | null {
  try {
    const buf = fs.readFileSync(absPath);
    if (isLikelyBinary(buf)) return null;
    if (buf.length > WI_MAX_FILE_SIZE) return null;
    return buf.toString('utf-8').split(/\r?\n/);
  } catch {
    return null;
  }
}

function buildSnippet(lines: string[], lineIdx: number): string {
  const start = Math.max(0, lineIdx - 1);
  const end = Math.min(lines.length, lineIdx + 2);
  const raw = lines.slice(start, end).join('\n');
  return raw.length > WI_MAX_SNIPPET_CHARS ? raw.slice(0, WI_MAX_SNIPPET_CHARS) + '…' : raw;
}

/** EXACT: live in-process literal scan (case-insensitive), zero-staleness. */
export function exactSearchWorkspace(opts: {
  workspaceRoot: string; workspaceId: string; projectId?: string | null;
  query: string; limit?: number; fileTypes?: string[]; pathPrefix?: string; signal?: AbortSignal;
}): WorkspaceSearchResponse {
  const t0 = Date.now();
  const limit = Math.min(opts.limit ?? WI_MAX_RESULTS, WI_MAX_RESULTS);
  const q = opts.query.toLowerCase();
  const results: WorkspaceSearchHit[] = [];
  let truncated = false;
  let scanned = 0;

  const walk = (dir: string) => {
    if (Date.now() - t0 > WI_SEARCH_TIMEOUT_MS) { truncated = true; return; }
    if (opts.signal?.aborted) { truncated = true; return; }
    if (scanned++ > WI_MAX_FILES_SCANNED) { truncated = true; return; }
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch { return; }
    for (const entry of entries) {
      if (results.length >= limit) { truncated = true; return; }
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!isIgnoredName(entry.name) && path.resolve(full) !== RUNTIME_DATA_DIR) walk(full);
      } else if (entry.isFile()) {
        if (isIgnoredName(entry.name)) continue;
        const rel = path.relative(opts.workspaceRoot, full).replace(/\\/g, '/');
        if (rel.startsWith('..') || path.isAbsolute(rel)) continue;
        if (opts.pathPrefix && !rel.startsWith(opts.pathPrefix.replace(/\\/g, '/'))) continue;
        if (opts.fileTypes && opts.fileTypes.length > 0 && !opts.fileTypes.some((t) => rel.endsWith(t.startsWith('.') ? t : `.${t}`))) continue;
        const lines = readFileLines(full);
        if (!lines) continue;
        for (let i = 0; i < lines.length; i++) {
          if (lines[i].toLowerCase().includes(q)) {
            results.push({
              relPath: rel, absPath: full, mode: 'exact', line: i + 1, lineResolved: true,
              snippet: buildSnippet(lines, i), workspaceId: opts.workspaceId,
            });
            if (results.length >= limit) { truncated = true; return; }
          }
        }
      }
    }
  };
  walk(opts.workspaceRoot);

  return {
    query: opts.query, mode: 'exact', chosenMode: 'exact',
    workspaceRoot: opts.workspaceRoot, workspaceId: opts.workspaceId, projectId: opts.projectId ?? null,
    results, total: results.length, truncated, durationMs: Date.now() - t0,
  };
}

/** TEXT: FTS5 bm25-ranked retrieval over the maintained index. */
export function textSearchWorkspace(opts: {
  workspaceRoot: string; workspaceId: string; projectId?: string | null;
  query: string; limit?: number; fileTypes?: string[]; pathPrefix?: string; signal?: AbortSignal;
}): WorkspaceSearchResponse {
  ensureWorkspaceIndexTables();
  const t0 = Date.now();
  const limit = Math.min(opts.limit ?? WI_MAX_RESULTS, WI_MAX_RESULTS);
  const results: WorkspaceSearchHit[] = [];
  let truncated = false;
  let error: string | undefined;

  // Build a safe FTS5 MATCH expression: bare tokens pass through; anything
  // with whitespace or reserved syntax becomes a quoted phrase (literal).
  const hasReserved = /[\s"*:^(){}[\]-]/.test(opts.query);
  const matchExpr = hasReserved ? `"${opts.query.replace(/"/g, ' ')}"` : opts.query;

  try {
    const rows = rawDb.prepare(`
      SELECT f.rel_path AS rel_path, f.abs_path AS abs_path, bm25(workspace_index_fts) AS rank
      FROM workspace_index_fts
      JOIN workspace_index_files f
        ON f.workspace_id = workspace_index_fts.workspace_id
       AND f.rel_path = workspace_index_fts.rel_path
      WHERE workspace_index_fts MATCH ? AND workspace_index_fts.workspace_id = ?
      ORDER BY rank
      LIMIT ?
    `).all(matchExpr, opts.workspaceId, limit) as Array<{ rel_path: string; abs_path: string; rank: number }>;
    const total = rows.length;
    for (const row of rows) {
      if (opts.signal?.aborted) { truncated = true; break; }
      if (opts.pathPrefix && !row.rel_path.startsWith(opts.pathPrefix.replace(/\\/g, '/'))) continue;
      if (opts.fileTypes && opts.fileTypes.length > 0 && !opts.fileTypes.some((t) => row.rel_path.endsWith(t.startsWith('.') ? t : `.${t}`))) continue;
      // Resolve a REAL line number by locating the first query token in the
      // file. If resolution fails, say so — never invent line numbers.
      const lines = readFileLines(row.abs_path);
      let line: number | undefined;
      let lineResolved = false;
      const probeToken = opts.query.split(/\s+/)[0]?.toLowerCase();
      if (lines && probeToken) {
        const idx = lines.findIndex((l) => l.toLowerCase().includes(probeToken));
        if (idx >= 0) { line = idx + 1; lineResolved = true; }
      }
      const snippetLine = line ? line - 1 : 0;
      results.push({
        relPath: row.rel_path, absPath: row.abs_path, mode: 'fts', line, lineResolved,
        snippet: lines && lines.length > 0 ? buildSnippet(lines, snippetLine) : '',
        score: Math.round(row.rank * 1000) / 1000, workspaceId: opts.workspaceId,
      });
      if (results.length >= limit) { truncated = true; break; }
    }
  } catch (err: any) {
    error = `FTS query failed: ${err?.message ?? 'unknown'}`;
    logger.warn('[WorkspaceIndex] workspace.search.failed', { workspaceId: opts.workspaceId, error, query: opts.query });
  }

  return {
    query: opts.query, mode: 'text', chosenMode: 'fts',
    workspaceRoot: opts.workspaceRoot, workspaceId: opts.workspaceId, projectId: opts.projectId ?? null,
    results, total: results.length, truncated, durationMs: Date.now() - t0, error,
  };
}

/** AUTO: choose the cheapest correct mechanism (P6). */
export function searchWorkspace(opts: {
  projectId?: string | null; query: string; mode?: WorkspaceSearchMode; limit?: number;
  fileTypes?: string[]; pathPrefix?: string; signal?: AbortSignal; rootOverride?: string;
}): WorkspaceSearchResponse {
  const t0 = Date.now();
  const query = (opts.query || '').trim();
  if (!query) {
    return {
      query: '', mode: opts.mode ?? 'auto', chosenMode: 'exact',
      workspaceRoot: '', workspaceId: '', projectId: opts.projectId ?? null,
      results: [], total: 0, truncated: false, durationMs: 0, error: 'Empty query.',
    };
  }
  const ctx = resolveWorkspaceContext(opts.projectId, opts.rootOverride);
  if (ctx.error || !ctx.workspaceRoot) {
    logger.warn('[WorkspaceIndex] workspace.search.failed', { error: ctx.error, query });
    return {
      query, mode: opts.mode ?? 'auto', chosenMode: 'exact',
      workspaceRoot: '', workspaceId: '', projectId: opts.projectId ?? null,
      results: [], total: 0, truncated: false, durationMs: Date.now() - t0, error: ctx.error,
    };
  }
  logger.info('[WorkspaceIndex] workspace.search.started', {
    workspaceId: ctx.workspaceId, projectId: ctx.projectId ?? null, query, mode: opts.mode ?? 'auto',
  });

  const mode = opts.mode ?? 'auto';
  const common = {
    workspaceRoot: ctx.workspaceRoot, workspaceId: ctx.workspaceId, projectId: ctx.projectId ?? null,
    query, limit: opts.limit, fileTypes: opts.fileTypes, pathPrefix: opts.pathPrefix, signal: opts.signal,
  };
  let resp: WorkspaceSearchResponse;
  if (mode === 'exact' || (mode === 'auto' && isExactPreferredQuery(query))) {
    resp = exactSearchWorkspace(common);
  } else if (mode === 'text') {
    resp = textSearchWorkspace(common);
  } else {
    // auto + multi-word → TEXT first; if the FTS query yields nothing and the
    // query is a plain token, fall back to exact (ground truth).
    resp = textSearchWorkspace(common);
    if (resp.results.length === 0 && !resp.error && !isExactPreferredQuery(query)) {
      resp = exactSearchWorkspace(common);
    }
  }

  logger.info('[WorkspaceIndex] workspace.search.completed', {
    workspaceId: ctx.workspaceId, projectId: ctx.projectId ?? null, query,
    chosenMode: resp.chosenMode, total: resp.total, truncated: resp.truncated,
    durationMs: resp.durationMs,
  });
  return resp;
}

/** Export the raw connection path for diagnostics (never content). */
export function workspaceIndexDbPath(): string {
  return rawDb.name;
}
